name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -yq bison flex
          sudo apt-get install -yq dos2unix
          sudo apt-get install -yq python python3
          sudo apt-get install build-essential
          dos2unix $(find -name *.sh)
          chmod +x test/compile.sh
          chmod +x test/unit/run.sh
          chmod +x test/syntax/check.sh
          chmod +x test/syntax/run.sh
          chmod +x test/semantics/run.sh
          chmod +x test/ir/run.sh
      - name: Build
        run: |
          cd src
          make
      - name: Unit Test
        run: |
          cd test/unit
          ./run.sh ../../src
      - name: Try Compile
        run: |
          cd test
          ./compile.sh
      - name: Test Syntax & Lexical
        run: |
          cd test/syntax
          ./run.sh ../../src/parser
      - name: Test Semantics
        run: |
          cd test/semantics
          ./run.sh ../../src/parser
      - name: Test IR
        run: |
          cd test/ir
          ./run.sh ../../src/parser